CREATE TABLE IF NOT EXISTS `company_info`(  
    `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `domain_id`  BIGINT UNSIGNED,
    `inn` VARCHAR(20),
    `name` VARCHAR(1000),
    `type` VARCHAR(1000),
    `segment` VARCHAR(255),
    `region` VARCHAR(500),
    `city` VARCHAR(255),
    `address` VARCHAR(255),
    `index` VARCHAR(20),
    `registration_date` DATE,
    `boss_name` VARCHAR(255),
    `boss_post` VARCHAR(255),
    `yandex_reviews` VARCHAR(500),
    `google_reviews` VARCHAR(500),
    `authorized_capital_type` VARCHAR(255),
    `authorized_capital_amount` INT(20),
    `registry_date` DATE,
    `registry_category` VARCHAR(255),
    `employees_number` INT(10),
    `main_activity`  VARCHAR(255),    
    FOREIGN KEY (`domain_id`) REFERENCES `domains` (`id`),
    UNIQUE KEY (`inn`)
);