CREATE TABLE IF NOT EXISTS `domain_info` (
    `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `domain_id` BIGINT UNSIGNED UNIQUE,
    `real_domain` VARCHAR(255),
    `title` TEXT,
    `description` TEXT,
    `keywords` TEXT,
    `city` TEXT,
    `inn` VARCHAR(255),
    `cms` VARCHAR(100),
    `hosting` VARCHAR(100),
    `is_ssl` BOOLEAN,
    `is_www` BOOLEAN,
    `is_https_redirect` BOOLEAN,
    `ip` VARCHAR(20),
    `country` VARCHAR(50),
    `tag_id` INT NULL,
    `status` VARCHAR(30) DEFAULT 'Отсутствует',
    `comment` TEXT,
    `is_ecommerce` BOOLEAN,
    `license_type` VARCHAR(50),
    `bitrix_id` BIGINT UNSIGNED,
    `last_updated` DATE,
    `last_migrated_to_bitrix` DATE,
    FOREIGN KEY (`domain_id`) REFERENCES `domains` (`id`),
    FOREIGN KEY (`tag_id`) REFERENCES `tags` (`id`),
    UNIQUE KEY (`real_domain`)
);