CREATE TABLE IF NOT EXISTS `domain_info` (
    `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `domain_id` BIGINT UNSIGNED UNIQUE,
    `title` TEXT,
    `description` TEXT,
    `keywords` TEXT,
    `city` TEXT,
    `inn` VARCHAR(255),
    `cms` VARCHAR(100),
    `hosting` VARCHAR(100),
    `is_ssl` BOOLEAN,
    `is_www` BOOLEAN,
    `is_https_redirect` BOOLEAN,
    `ip` VARCHAR(20),
    `tag_id` INT NULL,
    `status` VARCHAR(30) DEFAULT 'Отсутствует',
    `comment` TEXT,
    `bitrix_id` BIGINT UNSIGNED,
    FOREIGN KEY (`domain_id`) REFERENCES `domains` (`id`),
    FOREIGN KEY (`tag_id`) REFERENCES `tags` (`id`)
);