CREATE TABLE IF NOT EXISTS `domain_company_info`(  
    `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `inn_id`  BIGINT UNSIGNED,
    `inn` VARCHAR(20),
    `name` VARCHAR(1000),
    `type` VARCHAR(1000),
    `segment` VARCHAR(255),
    `region` VARCHAR(500),
    `city` VARCHAR(255),
    `address` VARCHAR(255),
    `post_index` VARCHAR(20),
    `registration_date` DATE,
    `boss_name` VARCHAR(255),
    `boss_post` VARCHAR(255),
    `yandex_reviews` VARCHAR(500),
    `google_reviews` VARCHAR(500),
    `authorized_capital_amount` VARCHAR(255),
    `registry_date` DATE,
    `registry_category` VARCHAR(255),
    `employees_number` INT(10),
    `main_activity`  VARCHAR(255),  
    `last_finance_year` INT(4),
    FOREIGN KEY (`inn_id`) REFERENCES `domain_inns` (`id`),
    UNIQUE KEY (`inn_id`)
);